### ISSUE TITLE
Do I inject the .dll file into brawlhalla process?

### ISSUE THREAD

**Issue by SaltyHampster** [MigDEV-Weeb/BrawlhallaComboBot#2]
I compiled the sln but to use I have to inject into process? if not, how so? 

Another question I have, is how do I know the bot is working once injected?

**Comment by MigDEV-Weeb** [comment]
Yes, you inject it into the Brawlhalla.exe Process. The cheat should open a cmd window, when injected. The project is under pause at the moment though, because I have to focus on school and other projects relevant to it. I´m sorry for my late answer
